//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opayo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opayo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;style&gt;
        ///    body {
        ///        text-align: center;
        ///        padding: 40px 0;
        ///        background: #EBF0F5;
        ///
        ///        display: flex;
        ///        align-items: center;
        ///    }
        ///
        ///    h1 {
        ///        color: #ffcc00;
        ///        font-family: &quot;Nunito Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif;
        ///        font-weight: 900;
        ///        font-size: 40px;
        ///        margin-bottom: 10px;
        ///    }
        ///
        ///    p {
        ///        color: #4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;style&gt;
        ///    body {
        ///        text-align: center;
        ///        padding: 40px 0;
        ///        background: #EBF0F5;
        ///
        ///        display: flex;
        ///        align-items: center;
        ///    }
        ///
        ///    h1 {
        ///        color: #bc6666;
        ///        font-family: &quot;Nunito Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif;
        ///        font-weight: 900;
        ///        font-size: 40px;
        ///        margin-bottom: 10px;
        ///    }
        ///
        ///    p {
        ///        color: #4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;style&gt;
        ///    body {
        ///        text-align: center;
        ///        padding: 40px 0;
        ///        background: #EBF0F5;
        ///
        ///        display: flex;
        ///        align-items: center;
        ///    }
        ///
        ///    h1 {
        ///        color: #88B04B;
        ///        font-family: &quot;Nunito Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif;
        ///        font-weight: 900;
        ///        font-size: 40px;
        ///        margin-bottom: 10px;
        ///    }
        ///
        ///    p {
        ///        color: #4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
    }
}
